### ISSUE TITLE
Exclamation marks create odd behavior and throw IllegalArgumentException

### ISSUE THREAD

**Issue by sage-t** [SpectraLogic/ds3_script#40]
```
spectra> \!true
!true
===> false
```

```
spectra> !true
[ERROR] Could not expand event
java.lang.IllegalArgumentException: !true: event not found
        at jline.console.ConsoleReader.expandEvents(ConsoleReader.java:864)
        at jline.console.ConsoleReader.finishBuffer(ConsoleReader.java:715)
        at jline.console.ConsoleReader.accept(ConsoleReader.java:2025)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2698)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2378)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2366)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2354)
        at jline.console.ConsoleReader$readLine$5.call(Unknown Source)
        at com.spectralogic.dsl.Tool.run(Tool.groovy:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1235)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1018)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1001)
        at org.codehaus.groovy.runtime.InvokerHelper.runScript(InvokerHelper.java:423)
        at org.codehaus.groovy.runtime.InvokerHelper$runScript.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
        at com.spectralogic.dsl.Tool.main(Tool.groovy:32)
```

**Comment by sage-t** [comment]
Fixed in 3.5.1
